### ISSUE TITLE
Odkaz na mapu je nějaký rozbitý

### ISSUE THREAD

**Issue by honzajavorek** [pyvec/pyvo-data#16]
![img_1490](https://cloud.githubusercontent.com/assets/283441/24517054/1b0d1a6a-157d-11e7-9090-16eb1291871d.PNG)

Tohle mi to na iOS udělá, když kliknu na odkaz "mapa" na stránce pro dnešní brněnské Pyvo. Když si to nechám otevřít v aplikaci, taky mi to nic kloudneho neukáže, akorát tam aspoň není oceán.

**Comment by messa** [comment]
Odkaz "(mapa)" je jen kotva na mapu na té stránce, asi myslíš odkaz na mapy.cz?

**Comment by messa** [comment]
To OpenStreetMap je nějaký tragický, ani se pořádně nenačítají dlaždice.

**Comment by messa** [comment]
Tohle by mohlo být lepší?

https://github.com/messa/pyvo.cz/commit/e786bd95ff4d9d03b5756c9845ff08c129fe6030

Odkaz pak vypadá takhle:

http://mapy.cz/zakladni?q=Skl%C3%ADpek%20kiwi.com&y=49.19041&x=16.5814139&z=18&id=16.5814139%2C49.19041&source=coor

**Comment by honzajavorek** [comment]
Sakra , myslel jsem, ze jsem to založil na Pyvo.cz. Ale neva. Mrknu na to ještě jak budu v Praze.

**Comment by honzajavorek** [comment]
Tak jsem to zkontroloval a je to zajímavé. Na mobilu jsem fakt klikal na Mapa a házelo mě to na mapy.cz, ne jako kotvu. Ale na počítači vidím kotvu. Každopádně dík za spravení, pokud na to narazím, založím lepší issue kdyžtak 🙂
