### ISSUE TITLE
Přidat info, co dělat, když se to nenasadí

### ISSUE THREAD

**Issue by messa** [pyvec/pyvo-data#251]
Jakože když se mělo nasadit, ale nenasadilo. 

Je někde dokumentované, jak se to nasazuje?

**Comment by encukou** [comment]
pyvo.cz má webhook, který stačí zavolat přes POST.
Obsahuje heslo, aby to nemohl volat *úplně* každý (je tam tedy spíš na rate limit než pro bezpečnost). Heslo je vidět v nastavení webhooků, máš-li dostatečný přístup k tomuhle repozitáři. Tam je i vidět jestli poslední hook prošel, příp. se dá poslat znovu.

Ale když nastane problém, je samozřejmě potřeba prohrabat log; to se popisuje blbě :(

**Comment by encukou** [comment]
Čili, nemám k tomu víc co říct než generické "když to nefunguje, stěžuj si maintainerovi" :(
