### ISSUE TITLE
Twitter bot

### ISSUE THREAD

**Issue by hroncok** [pyvec/pyvo-data#7]
Dohodli jsme se se @Sanqui, že napíše Twitter bota, který bude číst data z tohoto repozitáře a pokud je zítra nebo ten den Pyvo, tweetne o tom z nějakého poolu pseudonáhodnou hlášku o tom, že je v Praze/Brně/Ostravě Pyvo s tématem XYZ.

Momentální stav je takový, že to občas někdo udělá, ale většinou na to zapomeneme (já třeba). Dá se to jednou za čas naschedulovat na půl roku dopředu přes tweeddeck, ale problém je, že se teoreticky datum může změnit a že není info o tématu.

Já osobně bych bota na to nepsal, protože...

![xkcd: Automation](https://imgs.xkcd.com/comics/automation.png)

...ale sám se nabídl, že už nějaké kódy má, tak to vykopíruje a poskládá. Tak to třeba vyjde.

Udělá to do 8. ledna. Pokud se to nasadí a bude to fungovat, je třeba myslet na to a netweetovat to manuálně, při nejhorším půjde info na twitteru dvakrát.

**Comment by Sanqui** [comment]
Je to hotové!  Stačí tomu dát přístup k Twitter účtu a nahodit to jako každodenní cronjob.
https://github.com/Sanqui/pyvo-twitter

**Comment by hroncok** [comment]
Super, dobrá práce!

Kam to nasadíme?

**Comment by Sanqui** [comment]
Pokud Pyvec nemá vlastní VPSku (a už jsem něco takového zavětřil), můžu to klidně nahodit u sebe, když mi přihlásíš @naPyvo a dodáš klíče.

**Comment by hroncok** [comment]
@honzajavorek @encukou Víte něco o vlastní VPSce?

**Comment by honzajavorek** [comment]
My máme Roští.cz <http://xn--t-jga.cz>, kde jede zvlášť pyvo.cz a zvlášť
python.cz. Takže by se to asi dalo přilepit k tomu pyvo.cz, ale prosím
zdokumentovat kompletně v readmečkách na pyvo.cz repu - jak to nastavit na
serveru, jak je to nastaveny, co to dela, atd.

**Comment by hroncok** [comment]
A kdo nám to pomůže nasadit?

**Comment by honzajavorek** [comment]
Petr nebo ja. pyvo.cz ma obecne pod spravou spis Peta.

**Comment by encukou** [comment]
Na Roští to běží pod supervisorem, se kterým moc zkušeností nemám – vystačil jsem ci s copy-paste z rošťáckého návodu. Jestli si s tím někdo rozumí, můžu případně dát přístup.
Zatím si to zařazuju do svého TODO listu.

**Comment by hroncok** [comment]
Kouknem na to všichni 3 za týden v labu třeba.

**Comment by kvbik** [comment]
plus je tady dost supervisord-skilled lidi, napr: @aleszoulek [1]

[1] https://pypi.python.org/pypi/supervisor-wildcards/

**Comment by encukou** [comment]
[pyvo-twitter](https://github.com/pyvec/pyvo-twitter) is live; deployment notes are in the repo.
